---
- name: Manage a test S3 bucket
  hosts: all
  become: yes
 
  tasks:
  - name: Apply the S3 terraform template
    terraform:
      project_path: /home/ec2-user/s3/
      state: absent
      variables:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"