---
- name: Manage a test S3 bucket
  hosts: all
  become: yes
 
  tasks:
  - name: Apply the S3 terraform template
    terraform:
      project_path: /home/ec2-user/s3/
      state: planned
      plan_file: /home/ec2-user/s3/terraform.tfstate
    register: plan_output

  - name: Output terraform apply command and plan
    debug:
      msg: "{{ plan_output }}"