---
- name: Manage a test S3 bucket
  hosts: all
  become: yes

  tasks:
  - debug:
    msg: "testing with no tokens"
 
  # tasks:
  # - debug:
  #   msg: "key {{ aws_access_key }} and secret {{ aws_secret_key }}"

  # - name: Apply the S3 terraform template
  #   terraform:
  #     project_path: /home/ec2-user/s3/
  #     state: present
  #     variables:
  #       aws_access_key: "{{ aws_access_key }}"
  #       aws_secret_key: "{{ aws_secret_key }}"